spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/students?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC"
    username: "root"
    password: "1234"
    driverClassName: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 47.99.168.175
    port: 6370
    timeout: 5000
    password: myredis
  rabbitmq:
    host: 47.99.168.175
    port: 15672
    username: guest
    password: rabbitmq

server:
  port: 8888

mybatis-plus:
  config-location:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

