spring:
  datasource:
    url: "jdbc:mysql://47.99.168.175:3310/students?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC"
    username: "root"
    password: "123456"
    driverClassName: com.mysql.jdbc.Driver
server:
  port: 8888

mybatis-plus:
  config-location:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
